main: Principal.Main
name: TurboPlin
version: '1.0'
description: Le plugin du futur
load: POSTWORLD
author: IceStorm310
api-version: 1.16
commands:
  stat:
  factions:
  rejoindre:
  partir_factions:
  set_base:
  win:
  marqueur: